name: Python Script

on: [push]

jobs:

  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install Xvfb
      run: sudo apt-get install -y xvfb

    - name: Run script with Xvfb
      run: xvfb-run python script.py
